package com.flc.model;

import com.flc.exception.LessonFullException;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a single lesson offered at the Furzefield Leisure Centre.
 * Each lesson has a specific exercise type, day, time slot, and week number.
 * A lesson can accommodate a maximum of 4 members.
 *
 * @author FLC Development Team
 */
public class Lesson {

    /** Maximum number of members allowed per lesson. */
    public static final int MAX_CAPACITY = 4;

    private String lessonId;
    private ExerciseType exerciseType;
    private DayOfWeek day;
    private TimeSlot timeSlot;
    private int weekNumber;
    private List<Member> bookedMembers;
    private List<Review> reviews;

    /**
     * Constructs a new Lesson with the specified details.
     *
     * @param lessonId     unique identifier for the lesson (e.g., "L-W1-SAT-AM")
     * @param exerciseType the type of exercise for this lesson
     * @param day          the day of the week
     * @param timeSlot     the time slot (Morning, Afternoon, Evening)
     * @param weekNumber   the week number (1–8)
     */
    public Lesson(String lessonId, ExerciseType exerciseType, DayOfWeek day,
            TimeSlot timeSlot, int weekNumber) {
        this.lessonId = lessonId;
        this.exerciseType = exerciseType;
        this.day = day;
        this.timeSlot = timeSlot;
        this.weekNumber = weekNumber;
        this.bookedMembers = new ArrayList<>();
        this.reviews = new ArrayList<>();
    }

    /**
     * Books a member into this lesson.
     *
     * @param member the member to book
     * @throws LessonFullException if the lesson is at maximum capacity (4 members)
     */
    public void bookMember(Member member) throws LessonFullException {
        if (bookedMembers.size() >= MAX_CAPACITY) {
            throw new LessonFullException("Lesson " + lessonId + " is full (capacity: "
                    + MAX_CAPACITY + "). Cannot book member " + member.getName() + ".");
        }
        if (!bookedMembers.contains(member)) {
            bookedMembers.add(member);
        }
    }

    /**
     * Removes a member from this lesson.
     *
     * @param member the member to remove
     */
    public void removeMember(Member member) {
        bookedMembers.remove(member);
    }

    /**
     * Checks whether the lesson has available spaces.
     *
     * @return true if the number of booked members is less than the maximum
     *         capacity
     */
    public boolean isAvailable() {
        return bookedMembers.size() < MAX_CAPACITY;
    }

    /**
     * Gets the number of available spaces in this lesson.
     *
     * @return the number of available spaces
     */
    public int getAvailableSpaces() {
        return MAX_CAPACITY - bookedMembers.size();
    }

    /**
     * Adds a review to this lesson.
     *
     * @param review the review to add
     */
    public void addReview(Review review) {
        reviews.add(review);
    }

    /**
     * Calculates the average rating of all reviews for this lesson.
     *
     * @return the average rating (0.0 if no reviews exist)
     */
    public double getAverageRating() {
        if (reviews.isEmpty()) {
            return 0.0;
        }
        double sum = 0;
        for (Review r : reviews) {
            sum += r.getRating();
        }
        return sum / reviews.size();
    }

    /**
     * Calculates the total income generated by this lesson.
     *
     * @return the income (number of booked members × exercise price)
     */
    public double getIncome() {
        return bookedMembers.size() * exerciseType.getPrice();
    }

    // --- Getters and Setters ---

    /** @return the lesson ID */
    public String getLessonId() {
        return lessonId;
    }

    /** @param lessonId the lesson ID to set */
    public void setLessonId(String lessonId) {
        this.lessonId = lessonId;
    }

    /** @return the exercise type */
    public ExerciseType getExerciseType() {
        return exerciseType;
    }

    /** @param exerciseType the exercise type to set */
    public void setExerciseType(ExerciseType exerciseType) {
        this.exerciseType = exerciseType;
    }

    /** @return the day of the week */
    public DayOfWeek getDay() {
        return day;
    }

    /** @param day the day to set */
    public void setDay(DayOfWeek day) {
        this.day = day;
    }

    /** @return the time slot */
    public TimeSlot getTimeSlot() {
        return timeSlot;
    }

    /** @param timeSlot the time slot to set */
    public void setTimeSlot(TimeSlot timeSlot) {
        this.timeSlot = timeSlot;
    }

    /** @return the week number */
    public int getWeekNumber() {
        return weekNumber;
    }

    /** @param weekNumber the week number to set */
    public void setWeekNumber(int weekNumber) {
        this.weekNumber = weekNumber;
    }

    /** @return the list of booked members */
    public List<Member> getBookedMembers() {
        return bookedMembers;
    }

    /** @param bookedMembers the list of booked members to set */
    public void setBookedMembers(List<Member> bookedMembers) {
        this.bookedMembers = bookedMembers;
    }

    /** @return the list of reviews */
    public List<Review> getReviews() {
        return reviews;
    }

    /** @param reviews the list of reviews to set */
    public void setReviews(List<Review> reviews) {
        this.reviews = reviews;
    }

    @Override
    public String toString() {
        return String.format("Lesson[%s] Week %d - %s %s - %s (£%.2f) [%d/%d booked]",
                lessonId, weekNumber, day.getDisplayName(), timeSlot.getDisplayName(),
                exerciseType.getDisplayName(), exerciseType.getPrice(),
                bookedMembers.size(), MAX_CAPACITY);
    }
}
